version: '3'

services:
  db:
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=false"
    ports:
      - "5432:5432"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  nextcloud:
    image: linuxserver/nextcloud:19.0.3-ls100
    restart: always
    volumes:
      - ${NEXTCLOUD_DATA}:/data
      - ${NEXTCLOUD_CONFIG_DIR}:/config/www/nextcloud/config
      - ${NEXTCLOUD_NGINX_CONFIG_DIR}:/config/nginx/site-confs
      - ${NEXTCLOUD_PHP_CONFIG_DIR}:/config/php
    networks:
      - traefik
      - default
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - PGID=${PGID}
      - PUID=${PUID}
    depends_on:
      - db
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:${NEXTCLOUD_HOST}"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
      - "traefik.protocol=http"
      - "traefik.port=80"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.STSSeconds=15552000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  transmission:
    image: linuxserver/transmission:2.94-r1-ls6
    restart: always
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${BITTORRENT_DOWNLOAD_DIR}:/downloads/complete
      - transmission_incomplete:/downloads/incomplete
      - transmission_watch:/watch
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - "51643:51643"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:${TRANSMISSION_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=9091"
      - "traefik.frontend.passHostHeader=true"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  radarr:
    image: linuxserver/radarr:3.0.0.2704-ls10
    restart: always
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      # location where radarr will move films
      - ${RADARR_MEDIAS}:/movies
      # location where transmission download files
      - ${BITTORRENT_DOWNLOAD_DIR}:/downloads/complete
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:${RADARR_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=7878"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  sonarr:
    image: linuxserver/sonarr:3.0.3.713-ls180
    restart: always
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      # location where radarr will move films
      - ${SONARR_MEDIAS}:/tv
      # location where transmission download files
      - ${BITTORRENT_DOWNLOAD_DIR}:/downloads/complete
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:${SONARR_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=8989"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  mylar:
    image: linuxserver/mylar3:v0.4.9.1-ls6
    restart: always
    volumes:
      - ${MYLAR_CONFIG_DIR}:/config
      # location where radarr will move films
      - ${MYLAR_MEDIAS}:/comics
      # location where transmission download files
      - ${BITTORRENT_DOWNLOAD_DIR}:/downloads/complete
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=mylar"
      - "traefik.frontend.rule=Host:${MYLAR_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=8090"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  jackett:
    image: linuxserver/jackett:latest
    restart: always
    volumes:
      - ${JACKETT_CONFIG_DIR}:/config
      # map blackhole with transmission watch dir
      - transmission_watch:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:${JACKETT_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=9117"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  jellyfin:
    image: jellyfin/jellyfin:10.5.5
    restart: always
    volumes:
      - ${JELLYFIN_CONFIG_DIR}:/config
      - jellyfin_cache:/cache
      - ${RADARR_MEDIAS}:/movies
      - ${SONARR_MEDIAS}:/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - GIDLIST=44
#    devices:
#      - "/dev/dri/renderD128:/dev/dri/renderD128"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=jellyfin"
      - "traefik.frontend.rule=Host:${JELLYFIN_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=8096"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: always
    volumes:
      - ${HASS_CONFIG_DIR}:/config
    environment:
      - TZ=Europe/Paris
      - USERID=${PUID}
      - GROUPID=${PGID}
    networks:
      - traefik
    # expose other ports (mqtt) here
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "8080:8080" # The Web UI (enabled by --api)
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=hass"
      - "traefik.frontend.rule=Host:${HASS_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=8123"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

    shaarli:
      image: shaarli/shaarli:v0.12.1
      restart: always
      volumes:
        - shaarli-storage:/var/www/shaarli/data
        - shaarli-cache:/var/www/shaarli/cache
      networks:
        - traefik
      ports:
        - "8001:80"
      labels:
        - "traefik.docker.network=docker-homeserver_traefik"
        - "traefik.enable=true"
        - "traefik.backend=shaarli"
        - "traefik.frontend.rule=Host:${SHAARLI_HOST}"
        - "traefik.protocol=http"
        - "traefik.port=8001"
      logging:
        options:
          syslog-format: 'rfc5424'
          tag: "{{.Name}}"
    
  grafana:
    image: grafana/grafana:7.5.3
    restart: always
    depends_on:
      - influxdb
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
      - ${GRAFANA_CONFIG_DIR}:/etc/grafana
      - ${GRAFANA_PLUGIN_DIR}:/var/lib/grafana/plugins
    networks:
      - traefik
      - grafana
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:${GRAFANA_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=3000"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"
        
  influxdb:
    image: influxdb:1.7.10-alpine
    restart: always
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb:/var/lib/influxdb
      - ${INFLUDB_CONFIG_DIR}:/etc/influxdb
    ports:
      - "8086:8086"
    networks:
      - traefik
      - grafana
    labels:
      - "traefik.enable=false"
      # - "traefik.docker.network=docker-homeserver_traefik"
      # - "traefik.enable=true"
      # - "traefik.backend=influxdb"
      # - "traefik.frontend.rule=Host:${INFLUXDB_HOST}"
      # - "traefik.protocol=http"
      # - "traefik.port=8086"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
        tag: "{{.Name}}"

  loki:
    image: grafana/loki:2.2.1
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      # - loki-storage:/tmp/loki
      - ${LOKI_CONFIG_DIR}:/etc/loki
    networks:
      - grafana
    labels:
      - "traefik.enable=false"
      
  # promtail:
  #   image: grafana/promtail:2.0.0
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - /var/log:/var/log
  #     - ${PROMTAIL_CONFIG_DIR}:/etc/loki
  #   command: -config.file=/etc/promtail/config.yml
  #   ports:
  #     - "9080:9080"
  #   networks:
  #     - traefik
  #     - grafana
  #   labels:
  #     - "traefik.enable=false"

  portainer:
    image: portainer/portainer:1.23.1
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:${PORTAINER_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=9000"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

  pulseaudio:
    build:
      context: .
      dockerfile: ./docker_images/pulseaudio/Dockerfile
    restart: always
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast
    labels:
      - "traefik.enable=false"

  librespot:
    build:
      context: .
      dockerfile: ./docker_images/librespot/Dockerfile
    restart: always
    environment:
      - PULSEAUDIO_SERVER=pulseaudio:4317
    network_mode: "host"
    labels:
      - "traefik.enable=false"

  shairport:
    build:
      context: .
      dockerfile: ./docker_images/shairport-sync/Dockerfile
    restart: always
    environment:
      - PULSEAUDIO_SERVER=pulseaudio:4317
    network_mode: "host"
    volumes:
      - ${SHAIRPORT_CONFIG_DIR}:/config
    labels:
      - "traefik.enable=false"

  snapcast-server:
    build:
      context: .
      dockerfile: ./docker_images/snapcast-server/Dockerfile
    restart: always
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - snapcast:/var/cache/snapcast
      - ${SNAPCAST_CONFIG_DIR}:/config
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=snapcast"
      - "traefik.frontend.rule=Host:${SNAPCAST_HOST}"
      - "traefik.protocol=http"
      - "traefik.port=1780"

  traefik-proxy:
    image: traefik:1.7-alpine
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_CONF_FILE}:/traefik.toml
      - ${TRAEFIK_LETSENCRYPT_FILE}:/acme.json
    networks:
      - traefik
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"


  samba:
    image: dperson/samba:latest
    restart: always
    network_mode: host
    command: >
      -u "tok;blackbird;1000;1000"
      -s "Partage;/share;yes;no;yes"
      -s "tok;/tok;yes;no;no;tok;tok;tok"
    environment:
      - NMBD=true
      - TZ=Europe/Paris
      - USERID=${PUID}
      - GROUPID=${PGID}
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - ${NEXTCLOUD_DATA}/${NEXTCLOUD_FILER_USER}/files:/share
      - /mnt/btrfs/data/tok:/tok
    labels:
      - "traefik.enable=false"
    logging:
      options:
        syslog-format: 'rfc5424'
        tag: "{{.Name}}"

volumes:
  transmission_watch:
  transmission_incomplete:
  db:
  influxdb:
  grafana-storage:
  loki-storage:
  jellyfin_cache:
  portainer_data:
  snapcast:
  shaarli-storage:
  shaarli-cache:

networks:
  traefik:
  grafana: