version: '3'

services:
  db:
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:14-apache
    restart: always
    volumes:
      - ${NEXTCLOUD_DATA}:/var/www/html/data
      - ${CONFIG_DIR}/nextcloud:/var/www/html/config
      - nextcloud:/var/www/html
    networks:
      - traefik
      - default
    environment:
      - POSTGRES_HOST=db
    env_file:
      - nextcloud.env
    depends_on:
      - db
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:{{NEXTCLOUD_HOST}}"
      - "traefik.protocol=http"
      - "traefik.port=80"

  transmission:
    image: linuxserver/transmission:150
    restart: always
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${MOVIE_DOWNLOAD_DIR}:/downloads
      - transmission_watch:/watch
    env_file:
      - transmission.env
    networks:
      - traefik
    expose: 
      - 9091
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:{{TRANSMISSION_HOST}}"
      - "traefik.protocol=http"
      - "traefik.port=9091"

  jackett:
    image: linuxserver/jacket:344
    restart: always
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      # map blackhole with transmission watch dir
      - transmission_watch:/downloads
      - /etc/localtime:/etc/localtime:ro      
    env_file:
      - jackett.env
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:{{JACKETT_HOST}}"
      - "traefik.protocol=http"
      - "traefik.port=9117"

  radarr:
    image: linuxserver/radarr:142
    restart: always
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${RADARR_MOVIES}:/movies
      - ${RADARR_DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - jackett.env
    networks:
      - traefik
    labels:
      - "traefik.docker.network=docker-homeserver_traefik"
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:{{RADARR_HOST}}"
      - "traefik.protocol=http"
      - "traefik.port=7878"

  traefik-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_CONF_FILE}:/traefik.toml
      - ${TRAEFIK_LETSENCRYPT_FILE}:/acme.json
    networks:
      - traefik

volumes:
  transmission_watch:
  db:
  nextcloud:

networks:
  traefik: