#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config
mkdir -p ~/.config/pulse

[[ ! -f /config/shairport-sync.conf ]] && cp /defaults/shairport-sync.conf /config/shairport-sync.conf
[[ ! -f ~/.config/pulse/cookie ]] && touch ~/.config/pulse/cookie

# permissions
chown -R abc:abc \
	/config \
	~/.config

# allow read permission for cookie
chmod -R 755 /root

# fix user in shairport-sync-dbus.conf
sed -i "s/shairport-sync/abc/g" /etc/dbus-1/system.d/shairport-sync-dbus.conf