#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
	/config \
	/log \
	/var/cache/snapcast

# copy config
[[ ! -f /config/snapserver.conf ]] && cp \
	/defaults/snapserver.conf /config/snapserver.conf

# permissions
chown abc:abc \
	/config \
	/log \
	/var/cache/snapcast

if [ -n "$(ls -A /data 2>/dev/null)" ]; then
chown abc:abc \
	/var/cache/snapcast/*
fi
