#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
	/config \
	/log \
	/data 

# copy config
[[ ! -f /config/snapserver.json ]] && cp \
	/defaults/snapserver.conf /config/snapserver.json

# permissions
chown abc:abc \
	/config \
	/log \
	/data

if [ -n "$(ls -A /data 2>/dev/null)" ]; then
chown abc:abc \
	/data/*
fi
