#!/usr/bin/with-contenv bash
set -e
mkdir -p \
	~/.config/pulse

cp /etc/pulse/daemon.conf ~/.config/pulse/daemon.conf

# permissions
chown -R abc:abc \
	/etc/pulse \
	/run/pulse \
	~/.config/pulse


ls -l /root/.config/pulse
cat /root/.config/pulse//daemon.conf