# influxdb

rm "$BASE_DIR"/env/influxdb.env 2> /dev/null

INFLUDB_CONFIG_DIR="$CONFIG_DIR/influxdb"
INFLUXDB_DEFAULT_ADMIN_USER="admin"

SUBJECT="Infludb admin (Default ${INFLUXDB_DEFAULT_ADMIN_USER})"
INFLUXDB_ADMIN_USER=$(ask_value_with_default "$SUBJECT" "$INFLUXDB_DEFAULT_ADMIN_USER" "$INFLUXDB_ADMIN_USER")

SUBJECT="Infludb admin password"
INFLUXDB_ADMIN_PASSWORD=$(ask_value "$SUBJECT" "$INFLUXDB_ADMIN_PASSWORD")

{
    echo INFLUXDB_ADMIN_USER="${INFLUXDB_ADMIN_USER}"
    echo INFLUXDB_ADMIN_PASSWORD="${INFLUXDB_ADMIN_PASSWORD}"
    echo INFLUDB_CONFIG_DIR="${INFLUDB_CONFIG_DIR}"
} >> "$BASE_DIR"/env/influxdb.env
